### ISSUE TITLE
Renaming to python-quantities

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/quantities-feedstock#2]
How do we want to go about renaming from `quantities` to `python-quantities`? Maybe this can inform how we want to go about doing this in other cases where we have existing feedstocks that are not prefixed.

cc @pelson

**Comment by pelson** [comment]
Yes, good question. I have done a rename manually before, and honestly I think CircleCI was the only one to automatically redirect from the old repo. In fact, I had major problems renaming the project in AppVeyor. We should probably try to script it up in conda-smithy so that we can benefit from consistent renaming.
